import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  topContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '45%',
    flexDirection: 'row',
  },
  textBox: {
    color: '#fff',
    fontSize: 16,
    borderBottomColor: '#fff',
    borderBottomWidth: 1,
    marginTop: 10,
    marginHorizontal: 40,
    height: 40,
    padding: 10,
  },
  loginText: {
    color: '#fff',
    fontSize: 16,
    alignItems: 'flex-start',
    marginLeft: 40,
    marginTop: 20,
  },
  swiperText: {
    fontSize: 24,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'left',
    alignSelf: 'center',
    marginLeft: 30,
  },
  entrarButton: {
    backgroundColor: '#3a3967',
    padding: 10,
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 15,
    marginTop: 45,
    marginHorizontal: 40,
  },
  entrarButtonText: {
    color: '#fff',
    textAlign: 'center',
    margin: 10,
  },
  rastreador: {
    color: '#207dd2',
    fontSize: 31,
    marginTop: 0.1,
    textAlign: 'center',
    alignSelf: 'center',
  },
  mcgt: {
    color: '#f9f9f9',
    fontSize: 30,
    marginTop: 20,
    justifyContent: 'center',
    textAlign: 'center',
  },
  car: {
    resizeMode: 'contain',
    width: 130,
    bottom: 0,
  },
  linearGradient: {
    height: 260,
  },
  wrapper: {},
  swiperLogin:{
    width: '75%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  boxLogin: {
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    justifyContent: 'center',
  },
  boxLoginText: {
    color: '#FF311B',
    fontSize: 16,
    textAlign: 'center',
  },
  containerBoxLogin: {
    flexDirection: 'row',
  },
  boxLoginFacebook:{
    alignSelf: 'flex-start',
    width: '50%',
    height: 45,
    backgroundColor: '#2746E3',
    justifyContent: 'center',
  },
  boxLoginGoogle:{
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#E32727',
    justifyContent: 'center',
  },
  loginSocialText: {
    fontSize: 12,
    textAlign: 'center',
    color: '#fff',
  },
  loginEntrarText: {
    fontSize: 12,
    textAlign: 'center',
    color: '#00FF2B',
  },
  boxLeftLoginConfirm: {
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#000',
    justifyContent: 'center',
    borderRightColor: '#222',
    borderWidth: 1,
  },
  boxRightLoginConfirm: {
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#000',
    justifyContent: 'center',
  },
  topContainerConfirm: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '33%',
    flexDirection: 'row',
  },
  boxLoginConfirm: {
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  userText: {
    color: '#fff',
    fontSize: 12,
    textAlign: 'left',
    marginLeft: 15,
  },
  carOption:{
    backgroundColor: '#000',
    width: 132,
    height: 77,
    borderRightWidth: 0.2,
    borderColor: 'gray',
  },
  carBmw:{
    resizeMode: 'contain',
    width: 100,
    height: 60,
    alignSelf: 'center',
  },
  textCar:{
    color: 'white',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 2,
  },
  blackground:{
    backgroundColor: '#000',
    width: '100%',
    height: '100%',
    justifyContent: 'space-around',
  },
  activeBigText:{
    fontSize: 30,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 100,
    fontWeight: 'bold',
  },
  activeSmallText:{
    fontSize: 20,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 100,
    fontWeight: 'bold',
    marginBottom: 40,
  },
  btnVerde:{
    resizeMode: 'contain',
    width: 100,
    height: 100,
    alignSelf: 'center',
  },
  localActive: {
    width: '100%',
    backgroundColor: '#ff1d21',
    height: 50,
    marginBottom: 40,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  localActiveText:{
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  buscarSmallText:{
    fontSize: 20,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 50,
    fontWeight: 'bold',
    marginBottom: 30,
  },
  buscarBigText:{
    fontSize: 30,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 70,
    fontWeight: 'bold',
  },
  primeiraRoda: {
    borderRadius: 200,
    backgroundColor: '#005299',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
    width: 200,
  },
  segundaRoda: {
    position: 'absolute',
    backgroundColor: '#007eeb',
    borderRadius: 200,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 150,
    width: 150,
  },
  terceiraRoda: {
    position: 'absolute',
    borderRadius: 200,
    backgroundColor: '#0088ff',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
    width: 100,
  },
  loadText:{
    fontSize: 34,
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    color: '#fff',
  },
  style
})