import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  topContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '45%',
    flexDirection: 'row',
  },
  textBox: {
    color: '#fff',
    fontSize: 16,
    borderBottomColor: '#fff',
    borderBottomWidth: 1,
    marginTop: 10,
    marginHorizontal: 40,
    height: 40,
    padding: 10,
  },
  loginText: {
    color: '#fff',
    fontSize: 16,
    alignItems: 'flex-start',
    marginLeft: 40,
    marginTop: 20,
  },
  swiperText: {
    fontSize: 24,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'left',
    alignSelf: 'center',
    marginLeft: 30,
  },
  entrarButton: {
    backgroundColor: '#3a3967',
    padding: 10,
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 15,
    marginTop: 45,
    marginHorizontal: 40,
  },
  entrarButtonText: {
    color: '#fff',
    textAlign: 'center',
    margin: 10,
  },
  rastreador: {
    color: '#207dd2',
    fontSize: 31,
    marginTop: 0.1,
    textAlign: 'center',
    alignSelf: 'center',
  },
  mcgt: {
    color: '#f9f9f9',
    fontSize: 30,
    marginTop: 20,
    justifyContent: 'center',
    textAlign: 'center',
  },
  car: {
    resizeMode: 'contain',
    width: 130,
    bottom: 0,
  },
  linearGradient: {
    height: 260,
  },
  wrapper: {},
  swiperLogin:{
    width: '75%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  boxLogin: {
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    justifyContent: 'center',
  },
  boxLoginText: {
    color: '#FF311B',
    fontSize: 16,
    textAlign: 'center',
  },
  containerBoxLogin: {
    flexDirection: 'row',
  },
  boxLoginFacebook:{
    alignSelf: 'flex-start',
    width: '50%',
    height: 45,
    backgroundColor: '#2746E3',
    justifyContent: 'center',
  },
  boxLoginGoogle:{
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#E32727',
    justifyContent: 'center',
  },
  loginSocialText: {
    fontSize: 12,
    textAlign: 'center',
    color: '#fff',
  },
  loginEntrarText: {
    fontSize: 12,
    textAlign: 'center',
    color: '#00FF2B',
  },
  boxLeftLoginConfirm: {
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#000',
    justifyContent: 'center',
    borderRightColor: '#222',
    borderWidth: 1,
  },
  boxRightLoginConfirm: {
    alignSelf: 'flex-end',
    width: '50%',
    height: 45,
    backgroundColor: '#000',
    justifyContent: 'center',
  },
  topContainerConfirm: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '33%',
    flexDirection: 'row',
  },
  boxLoginConfirm: {
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  boxLoginConfirmModal: {
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderTopColor: '#222',
  },
  modalBox:{
    width: '100%',
    height: 45,
    backgroundColor: '#000',
    borderBottomColor: '#222',
    borderWidth: 1,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  userText: {
    color: '#fff',
    fontSize: 12,
    textAlign: 'left',
    marginLeft: 12,
  },
  carOption:{
    backgroundColor: '#000',
    width: 132,
    height: 77,
    borderRightWidth: 0.2,
    borderColor: 'gray',
  },
  carOption1:{
    backgroundColor: '#000',
    width: '101%',
    height: '100%',
    borderRightWidth: 0.2,
    borderColor: 'gray',
    borderBottomWidth: 0.2,
    flexDirection: 'row',
    justifyContent: 'center'
  },
  carBmw:{
    resizeMode: 'contain',
    width: 100,
    height: 60,
    alignSelf: 'center',
  },
  carBmw1:{
    resizeMode: 'contain',
    width: 100,
    height: 60,
    alignSelf: 'center',
    justifyContent: 'center',
    marginLeft: 20,
  },
  carBmwModal:{
    resizeMode: 'contain',
    width: 300,
    height: 80,
    alignSelf: 'center',
  },
  textCar:{
    color: 'white',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 2,
  },
  textCar1:{
    color: 'white',
    fontSize: 12,
    textAlign: 'center',
    marginVertical: 30,
    marginLeft: 15,
  },
  blackground:{
    backgroundColor: '#000',
    width: '100%',
    height: '100%',
    justifyContent: 'space-around',
  },
  activeBigText:{
    fontSize: 30,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 100,
    fontWeight: 'bold',
  },
  activeSmallText:{
    fontSize: 20,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 100,
    fontWeight: 'bold',
    marginBottom: 40,
  },
  btnVerde:{
    resizeMode: 'contain',
    width: 100,
    height: 100,
    alignSelf: 'center',
  },
  localActive: {
    width: '100%',
    backgroundColor: '#ff1d21',
    height: 50,
    marginBottom: 40,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  localActiveText:{
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  buscarSmallText:{
    fontSize: 20,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 50,
    fontWeight: 'bold',
    marginBottom: 30,
  },
  buscarBigText:{
    fontSize: 30,
    color: '#fff',
    textAlign: 'center',
    marginHorizontal: 70,
    fontWeight: 'bold',
  },
  primeiraRoda: {
    borderRadius: 200,
    backgroundColor: '#005299',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
    width: 200,
    marginTop: 60,
  },
  segundaRoda: {
    position: 'absolute',
    backgroundColor: '#007eeb',
    borderRadius: 200,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 150,
    width: 150,
  },
  terceiraRoda: {
    position: 'absolute',
    borderRadius: 200,
    backgroundColor: '#0088ff',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
    width: 100,
  },
  loadText:{
    fontSize: 34,
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    color: '#fff',
  },
  headerGps: {
    width: '85%',
    height: 60,
    backgroundColor: 'black',
    alignSelf: 'flex-end',  
    position: 'absolute',
    bottom: 660,
    justifyContent: 'center',
  },
  headerEditar: {
    width: '85%',
    height: 60,
    backgroundColor: 'black',
    alignSelf: 'flex-end',  
    justifyContent: 'center',
  },
  textGps:{
    fontSize: 20,
    color: 'white',
    textAlign: 'left',
    marginLeft: 20,
  },
  boxGps: {
  width: '100%',
    height: 50,
    backgroundColor: '#000',
    borderBottomColor: '#111',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBoxTop:{
    fontSize: 16,
    color: 'green',
    textAlign: 'center',
  },
  textBoxBot:{
    fontSize: 16,
    color: 'red',
    textAlign: 'center',
  },
  voltarBox:{
    height: 50,
    width: '100%',
    backgroundColor: '#0da500',
    justifyContent: 'center',
  },
  deletarBox:{
    height: 45,
    width: '50%',
    backgroundColor: '#ff0000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textVoltar:{
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    backgroundColor: 'black',
    width: '100%',
    height: 470,
  },
  button: {
    backgroundColor: '#0087ff',
    borderRadius: 100,
    width: 35,
    height: 35,
    alignSelf: 'flex-end',
    marginRight: 20,
    bottom: 10,
  },
  buttonOpen: {
    backgroundColor: "#0087ff",
  },
  buttonClose: {
    backgroundColor: "#0087ff",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center"
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center"
  },
  topModalText:{
    color: 'white',
    marginVertical: 30,
    textAlign: 'center',
    fontSize: 26,
  },
  botModalText:{
    color: 'white',
    marginTop: 20,
    marginBottom: 80,
    textAlign: 'center',
    fontSize: 16,
  },
  editarDados:{
    backgroundColor: 'black',
    width: '100%',
    height: '12%',
    justifyContent: 'center',
  },
  textSettings: {
    fontSize: 14,
    color: 'white',
    textAlign: 'left',
    marginLeft: 30,
  },
  textSettingsTop:{
    fontSize: 28,
    color: 'white',
    textAlign: 'left',
    marginLeft: 30,
  },
})